<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Symfony\\Polyfill\\Ctype\\' => array($vendorDir . '/symfony/polyfill-ctype'),
    'Symfony\\Component\\Yaml\\' => array($vendorDir . '/symfony/yaml'),
    'Phalcon\\' => array($vendorDir . '/phalcon/incubator/Library/Phalcon'),
    'Mdanter\\Ecc\\Tests\\' => array($vendorDir . '/mdanter/ecc/tests/unit'),
    'Mdanter\\Ecc\\' => array($vendorDir . '/mdanter/ecc/src'),
    'Doctrine\\Instantiator\\' => array($vendorDir . '/doctrine/instantiator/src/Doctrine/Instantiator'),
    'BitWasp\\BitcoinLib\\' => array($vendorDir . '/bitwasp/bitcoin-lib/src'),
);
